import os

from dotenv import load_dotenv


load_dotenv()

# Infra
DATABASE_URL = os.getenv("DATABASE_URL")
ENV_CONFIG = os.getenv("ENV_CONFIG")
SUPABASE_URL = os.getenv("SUPABASE_URL")
TEAMS_BUCKET = os.getenv("TEAMS_BUCKET")
FRONTEND_URL = os.getenv("FRONTEND_URL")

# Security
MIGRATIONS_PWD = os.getenv("MIGRATIONS_PWD")
SWAGGER_USERNAME = os.getenv("SWAGGER_USERNAME")
SWAGGER_PASSWORD = os.getenv("SWAGGER_PASSWORD")
PASSWORD_PEPPER = os.getenv("PASSWORD_PEPPER")
SALT_ROUNDS = int(os.getenv("SALT_ROUNDS"))
JWT_KEY = os.getenv("JWT_KEY")
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 8
REFRESH_TOKEN_SECURE_BOOL = bool(os.getenv("REFRESH_TOKEN_SECURE_BOOL"))
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
SUPER_USER_PWD = os.getenv("SUPER_USER_PWD")

# Bussiness logic
FRIENDLY_CHAMPIONSHIP_NAME = "Amistosos"
BEFORE_SYSTEM_CHAMPIONSHIP_NAME = "Antes do Forquilha"

# Email
APP_EMAIL = os.getenv("APP_EMAIL")
APP_EMAIL_PASSWORD = os.getenv("APP_EMAIL_PASSWORD")
